routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return redirect()->route('home');
});*/

Auth::routes();

// Route::get('/test',function(){
// 	return App\User::find(1)->profile;
// });
// Route::get('/', 'HomeController@index')->name('home');
// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/oil_field', 'HomeController@home')->name('home');


Route::get('/', 'HomeController@home')->name('home');
Route::get('/home', 'HomeController@home')->name('home');
Route::get('/oil_field', 'HomeController@home')->name('home');


Route::resource('/users', 'admin\UserController');
Route::get('/myProfile', 'admin\UserController@myProfile')->name('myProfile');
Route::post('/myProfile', 'admin\UserController@myProfileUpdate')->name('myProfileUpdate');

Route::resource('/settings', 'admin\SettingsController');

Route::resource('/inventory', 'admin\InventoryController');
Route::post('/getSubcategory', 'admin\InventoryController@getSubcategory')->name('getSubcategory');
Route::post('/getInventoryInfo', 'admin\InventoryController@getInventoryInfo')->name('getInventoryInfo');
Route::post('/getResourceInfoBySubcat', 'admin\InventoryController@getResourceInfoBySubcat')->name('getResourceInfoBySubcat');
Route::post('/getVariablesBySubcat', 'admin\InventoryController@getVariablesBySubcat')->name('getVariablesBySubcat');
Route::post('/getImagesBySubcat', 'admin\InventoryController@getImagesBySubcat')->name('getImagesBySubcat');
Route::post('/getUnitDetailsBySubcat', 'admin\InventoryController@getUnitDetailsBySubcat')->name('getUnitDetailsBySubcat');
Route::post('/unitProperties', 'admin\InventoryController@unitProperties')->name('unitProperties');
Route::post('/unitPropertiesDlt', 'admin\InventoryController@unitPropertiesDlt')->name('unitPropertiesDlt');


Route::resource('/customers', 'admin\CustomerController');
Route::get('/qbCallback', 'admin\CustomerController@qbCallback');
Route::get('/qbCustomer', 'admin\CustomerController@qbCustomer')->name('qbCustomer');
Route::get('/qbRefreshToken', 'admin\CustomerController@qbRefreshToken')->name('qbRefreshToken');
Route::post('/importQbData', 'admin\CustomerController@importQbData')->name('importQbData');
Route::get('/synchronizeCustomer', 'admin\CustomerController@synchronizeCustomer')->name('synchronizeCustomer');
Route::get('/synchronizeQb', 'admin\CustomerController@synchronizeQb')->name('synchronizeQb');
Route::get('/insertQbCustomer', 'admin\CustomerController@insertQbCustomer')->name('insertQbCustomer');
Route::get('/discardQbCustomer', 'admin\CustomerController@discardQbCustomer')->name('discardQbCustomer');
Route::get('/singleCustomerQB', 'admin\CustomerController@singleCustomerQB')->name('singleCustomerQB');

Route::get('/creditApp/{id}/edit', 'admin\CustomerController@creditAppEdit')->name('creditAppEdit');
Route::get('/creditApp/{id}', 'admin\CustomerController@creditAppShow')->name('creditAppShow');
Route::post('/creditAppUpdate', 'admin\CustomerController@creditAppUpdate')->name('creditAppUpdate');
Route::get('/creditAppDelete/{id}', 'admin\CustomerController@creditAppDelete')->name('creditAppDelete');
Route::get('creditApp/accessCode/{token}', 'admin\CustomerController@creditAppToken');
Route::post('creditApp', 'admin\CustomerController@creditAppCustomer')->name('creditAppCustomer');
Route::post('creditAppUpdateForCustomer', 'admin\CustomerController@creditAppUpdateForCustomer')->name('creditAppUpdateForCustomer');
Route::get('creditAppMessage', 'admin\CustomerController@creditAppMessage')->name('creditAppMessage');
Route::get('creditAppPdf/{id}', 'admin\CustomerController@creditAppPdf')->name('creditAppPdf');



Route::resource('/products', 'admin\ProductController');

Route::resource('/vendors', 'admin\VendorController');
Route::get('/getQbVendor', 'admin\VendorController@getQbVendor')->name('getQbVendor');
Route::get('/synchronizeEvosVendor', 'admin\VendorController@synchronizeEvosVendor')->name('synchronizeEvosVendor');
Route::get('/synchronizeQbVendor', 'admin\VendorController@synchronizeQbVendor')->name('synchronizeQbVendor');
Route::get('/insertQbVendor', 'admin\VendorController@insertQbVendor')->name('insertQbVendor');
Route::get('/discardQbVendor', 'admin\VendorController@discardQbVendor')->name('discardQbVendor');


Route::post('/getImage', 'admin\VendorController@getImage')->name('getImage');

Route::resource('/quotation', 'admin\QuotationController');

Route::post('/getService', 'admin\QuotationController@getService')->name('getService');

Route::post('/getServiceResourceInfo', 'admin\QuotationController@getServiceResourceInfo')->name('getServiceResourceInfo');
Route::post('/getRentalResourceInfo', 'admin\QuotationController@getRentalResourceInfo')->name('getRentalResourceInfo');
Route::post('/getAddress', 'admin\QuotationController@getAddress')->name('getAddress');

Route::post('/addVariableSection', 'admin\InventoryController@addVariableSection')->name('addVariableSection');

Route::post('/variableEnableDisable', 'admin\InventoryController@variableEnableDisable')->name('variableEnableDisable');


Route::post('/getCustomerDetails', 'admin\QuotationController@getCustomerDetails')->name('getCustomerDetails');
Route::post('/updateCustomerQuoteInfo', 'admin\QuotationController@updateCustomerQuoteInfo')->name('updateCustomerQuoteInfo');

Route::resource('/insurance', 'admin\InsuranceController');
Route::get('insurance/accessCode/{token}', 'admin\InsuranceController@insuranceToken');
Route::post('insurance/pdf', 'admin\InsuranceController@getPdf')->name('getPdf');
Route::post('findInsurance', 'admin\InsuranceController@findInsurance')->name('findInsurance');
Route::post('generateInsuranceReport', 'admin\InsuranceController@generateInsuranceReport')->name('generateInsuranceReport');
Route::post('agreement', 'admin\InsuranceController@agreement')->name('agreement');
Route::get('agreementMessage', 'admin\InsuranceController@agreementMessage')->name('agreementMessage');
Route::post('getInsuranceImage', 'admin\InsuranceController@getInsuranceImage')->name('getInsuranceImage');
Route::post('generateAgreementReport', 'admin\InsuranceController@generateAgreementReport')->name('generateAgreementReport');
Route::get('agreementPdf/{id}', 'admin\InsuranceController@agreementPdf')->name('agreementPdf');
Route::post('/autocomplete', 'admin\InsuranceController@autocomplete')->name('autocomplete');



Route::post('deleteInventoryUnit', 'admin\InventoryController@deleteInventoryUnit')->name('deleteInventoryUnit');

Route::get('test', 'admin\InventoryController@test')->name('test');

Route::get('agreement', 'admin\InsuranceController@agreement')->name('agreement');

Route::get('subcontractor_pdf', 'admin\InsuranceController@subcontractor_pdf')->name('subcontractor_pdf');
Route::get('rental_pdf', 'admin\InsuranceController@rental_pdf')->name('rental_pdf');
Route::get('owner_pdf', 'admin\InsuranceController@owner_pdf')->name('owner_pdf');

Route::get('creditApplication', 'admin\CustomerController@creditApplication')->name('creditApplication');
Route::get('creditApplicationEmail', 'admin\CustomerController@creditApplicationEmail')->name('creditApplicationEmail');
Route::get('creditApplicationPdf', 'admin\CustomerController@creditApplicationPdf')->name('creditApplicationPdf');

Route::resource('/jobChecklist', 'admin\JobChecklistController');


Route::get('/users/make_admin/{id}','admin\UserController@make_admin')->name('make.admin');
Route::get('/users/make_agent/{id}','admin\UserController@make_agent')->name('make.agent');

app/Http/Controllers/admin/InventoryController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\Models\Category;
use App\Models\Subcategory;
use App\Models\ResourceParameter;
use App\Models\Inventory;
use App\Models\InventoryUnit;
use App\Models\Variable;
use App\Models\VariableParameter;
use App\Models\VariableSection;
use App\Models\Image;
use Validator;

class InventoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
	public function index(){
        $cat = Category::where('type', 'inventory')->get();
        $subcat = Subcategory::with(['category'])->where('type', 'inventory')->get();
        $variables = Variable::where('type', 'inventory')->get();
        $inventory = Inventory::with(['category', 'subcategory'])->orderBy('id', 'asc')->groupBy('subcat_id')->get();

        if(request()->ajax()){
            if($_GET['type'] == 'cat'){
                $cat = Category::with(['subcat', 'subcat.resources'])->where('type', 'inventory')->orderByRaw(" IF(category_name RLIKE '^[a-z]', 1, 2), category_name ");;
                return datatables()->of($cat)
                        ->addColumn('action', function($data){
                            $button = '<form action="' .route("inventory.destroy",[$data->id, "type" => "cat"]). '" method="POST">' ;
                            $button .= '<a href="' .route('inventory.edit', [$data->id, 'type' => 'cat']). '" class="btn btn-link btn-success btn-just-icon edit"><i class="material-icons">edit</i></a>';       
                            $button .= '<input name="_token" type="hidden" value="' .csrf_token(). '">';
                            $button .= '<input type="hidden" name="_method" value="DELETE">';
                            $button .= '<button type="submit" class="btn btn-link btn-danger btn-just-icon remove" onclick="return confirm(\'Are you sure you want to delete?\');"><i class="material-icons">close</i></button>';
                            $button .= '</form>';
                            
                            return $button;
                        })
                        ->rawColumns(['action'])
                        ->make(true);
            }
            else if($_GET['type'] == 'subcat'){
                $subcat = Subcategory::with(['category', 'resources'])->where('type', 'inventory')->orderByRaw(" IF(subcategory_name RLIKE '^[a-z]', 1, 2), subcategory_name ");
                return datatables()->of($subcat)
                        ->addColumn('action', function($data){
                            $button = '<form action="' .route("inventory.destroy",[$data->id, "type" => "subcat"]). '" method="POST">' ; 
                             $button .= '<a href="' .route('inventory.edit', [$data->id, 'type' => 'subcat']). '" class="btn btn-link btn-success btn-just-icon edit"><i class="material-icons">edit</i></a>';      
                            $button .= '<input name="_token" type="hidden" value="' .csrf_token(). '">';
                            $button .= '<input type="hidden" name="_method" value="DELETE">';
                            $button .= '<button type="submit" class="btn btn-link btn-danger btn-just-icon remove" onclick="return confirm(\'Are you sure you want to delete?\');"><i class="material-icons">close</i></button>';
                            $button .= '</form>';
                            
                            return $button;
                        })
                        ->rawColumns(['action'])
                        ->make(true);
            }
        }

        return view('admin.inventory.index', compact('cat', 'subcat', 'variables', 'inventory'));
	}


    public function create(){

        $cat = Category::where('type', 'inventory')->get();
        $subcat = Subcategory::where('type', 'inventory')->get();
        $variables = Variable::where('type', 'inventory')->where('enable_disable', 1)->get();

        return view('admin.inventory.create', compact('cat', 'subcat', 'variables'));
    }
    

    public function store(Request $request){

        if($request->tab == 'category')
            return $this->category($request, 'store');
        elseif($request->tab == 'subcategory'){
            return $this->subCategory($request, 'store');
        }
        elseif($request->tab == 'variable')
            return $this->variable($request, 'store');
        elseif($request->tab == 'inventory')
            return $this->inventory($request, 'store');
        

    }

    public function category($request, $type){
        $validator = Validator::make($request->all(), [
            'category_name' => 'required|unique:categories',
        ]);

        if($type == 'store'){
            if($validator->fails()){
                return back()->withErrors($validator)->withInput(['tab'=>'profile']);
            }
            else{
                Category::create($request->except(['tab']));
                session()->flash('success', 'Successfully added category');  
                return back()->withInput(['tab'=>'profile']);  
            }
                
        }
        elseif($type == 'update'){
            Category::whereId($request->p_key)->update($request->except(['tab', 'p_key', '_token', '_method']));
            session()->flash('success', 'Successfully updated category');    
            return back();
        }

        
    }

    public function subcategory($request, $type){
        $validator = Validator::make($request->all(), [
            'cat_id' => 'required',
            'subcategory_name' => 'required|unique:subcategories',
        ]);

        if($type == 'store'){
            if($validator->fails()){
                    return back()->withErrors($validator)->withInput(['tab'=>'messages']);
            }
            else{
                $subcat = Subcategory::create([
                    "cat_id" => $request->cat_id,
                    "subcategory_name" => $request->subcategory_name,
                    "type" => 'inventory',
                ]);

                $params = [];
                $unit_param_name = $request->unit_param_name;
                foreach($unit_param_name as $key=>$value){
                    $params[] = [
                        'subcat_id' => $subcat->id,
                        'unit_param_name' => $request->unit_param_name[$key],
                        'unit_param_data_type' => $request->unit_param_data_type[$key],
                        "created_at" =>  \Carbon\Carbon::now(), # new \Datetime()
                        "updated_at" => \Carbon\Carbon::now(),  # new \Datetime()
                    
                    ];
                }
                ResourceParameter::insert($params);

                session()->flash('success', 'Successfully added subcategory');
                return back()->withInput(['tab'=>'messages']);
            }
    
        }
        elseif($type == 'update'){
           Subcategory::whereId($request->p_key)->update([
                "cat_id" => $request->cat_id,
                "subcategory_name" => $request->subcategory_name,
                "type" => 'inventory',
           ]);

            $unit_param_key = $request->unit_param_key;
            $unit_param_rows = ResourceParameter::where('subcat_id', $request->p_key)->get();
            if($unit_param_key){
                foreach ($unit_param_rows as $rowdata) {
                       if(!in_array($rowdata->id, $unit_param_key)){
                          ResourceParameter::where('id', $rowdata->id)->delete();  
                       }
                }
            }
            else{
                foreach ($unit_param_rows as $rowdata) {
                    ResourceParameter::where('id', $rowdata->id)->delete();  
                }
            }

            $unit_param_name = $request->unit_param_name;
            if($unit_param_name){
                foreach($unit_param_name as $key=>$value){
                        if(isset($request->unit_param_key[$key])){
                            ResourceParameter::where('id', $request->unit_param_key[$key])->update([
                                'subcat_id' => $request->p_key,
                                'unit_param_name' => $request->unit_param_name[$key],
                                'unit_param_data_type' => $request->unit_param_data_type[$key],
                                "created_at" =>  \Carbon\Carbon::now(), # new \Datetime()
                                "updated_at" => \Carbon\Carbon::now(),  # new \Datetime()
                            ]);
                        }
                        else{
                            ResourceParameter::create([
                                'subcat_id' => $request->p_key,
                                'unit_param_name' => $request->unit_param_name[$key],
                                'unit_param_data_type' => $request->unit_param_data_type[$key],
                            ]);
                        }
                    }
            }

           session()->flash('success', 'Successfully updated subcategory');
           return back();   
        }
        
    }

    
    public function variable($request, $type){
        if($type == 'store'){
            $var = Variable::create([
                'type' => 'inventory',
                'variable_name' => $request->variable_name,
            ]);
            $var_param_name = $request->var_param_name;
            if($var_param_name){
                foreach ($var_param_name as $key => $value) {
                    VariableParameter::create([ 
                        'var_id' => $var->id,
                        'var_param_name' => $request->var_param_name[$key],
                        'var_param_data_type' => $request->var_param_data_type[$key],
                        'var_param_value_type' => $request->var_param_value_type[$key],
                        'var_param_value' => $request->var_param_value[$key],  

resources/views/admin/inventory/categoryEdit.blade.php
@extends('layouts.master')

@section('content')

        <div class="content">
          <div class="content">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-12 mx-auto card_holder_box">
                  
                  
                  <div class="card">
                  <div class="card-header card-header-tabs card-header-rose">
                    <div class="nav-tabs-navigation">
                      <div class="nav-tabs-wrapper">
                        
                        <ul class="nav nav-tabs" data-tabs="tabs">
                          <li class="nav-item">
                            <a class="nav-link active" href="#profile" data-toggle="tab">
                              <i class="material-icons">ballot</i> Edit Category
                              <div class="ripple-container"></div>
                            </a>
                          </li>
                          
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div style="margin-top: 15px;">
                      @include('partials.messages')
                  </div>

                  <div class="card-body">
                     
                        <div class="card edit_category_inner_card">
                          <div class="card-header card-header-rose card-header-text">
                            
                          </div>

                          <div class="card-body col-md-12 mx-auto increased_margin_t_cardbody">
                            <form method="post" action="{{ route('inventory.update', $cat->id) }}" class="form-horizontal">
                            @csrf
                            @method('PUT')

                            <input type="hidden" name="tab" value="category">
                            <input type="hidden" name="p_key" value="{{$cat->id}}">

                                <div class="row sub_holder">
                                  <div class="col-md-12 input_wrapper">
                                    <div class="form-group bmd-form-group is-filled">
                                      <label for="subcategory_name" class="bmd-label-floating input_label">Category Name *</label>
                                      <input type="text" class="form-control form_input_field" id="category_name" name="category_name" required="true" aria-required="true" value="{{$cat->category_name}}">
                                    </div>
                                  </div>
                                </div>
                              <div class="form-group bmd-form-group save_btn_wrapper">
                                <button type="submit" class="btn save_btn custom-btn-one">Update</button>
                              </div>
                          </form>
                          </div>
                      </div>


                     
                  </div>
                </div>
  
  
  
                </div>
              </div>
          </div>
        </div>
      </div>

@endsection

resources/views/admin/inventory/new_form_design.blade.php
@extends('layouts.master')

@section('content')

<div class="content manage-inventory-content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12 mx-auto">
       <h2> New form design</h2>
      </div>
    </div>
  </div>
</div>


@endsection

resources/views/admin/inventory/subcategoryEdit.blade.php
@extends('layouts.master')

@section('content')

        <div class="content">
          <div class="content">
            <div class="container-fluid">
              <div class="row">
                <div class="col-md-12 mx-auto card_holder_box">
                  
                  
                  <div class="card">
                  <div class="card-header card-header-tabs card-header-rose">
                    <div class="nav-tabs-navigation">
                      <div class="nav-tabs-wrapper">
                        
                        <ul class="nav nav-tabs" data-tabs="tabs">
                          <li class="nav-item">
                            <a class="nav-link active" href="#profile" data-toggle="tab">
                              <i class="material-icons">ballot</i> Edit Sub Category
                              <div class="ripple-container"></div>
                            </a>
                          </li>
                          
                        </ul>
                      </div>
                    </div>
                  </div>

                  <div style="margin-top: 15px;">
                      @include('partials.messages')
                  </div>

                  <div class="card-body">
                     
                        <div class="card edit_category_inner_card">
                          <div class="card-header card-header-rose card-header-text">
                            
                          </div>

                          <div class="card-body col-md-12 mx-auto increased_margin_t_cardbody">
                            <form method="post" action="{{ route('inventory.update', $subcat->id) }}" class="form-horizontal">
                            @csrf
                            @method('PUT')

                            <input type="hidden" name="tab" value="subcategory">
                            <input type="hidden" name="p_key" value="{{$subcat->id}}">

                                <div class="row sub_holder">
                                  <div class="col-md-6 custom_select2_col">
                                    <div class="form-group custom-form-select">
                                      <select class="custom-select hasvalue select2" id="category-custom-select" name="cat_id">
                                        <option class="form-select-placeholder"></option>
                                        @foreach($cat as $rowdata)
                                          <option value="{{$rowdata->id}}" @if($rowdata->id == $subcat->cat_id) selected @endif>{{$rowdata->category_name}}</option>
                                        @endforeach
                                      </select>
                                      <div class="form-element-bar">
                                      </div>
                                      <label class="form-element-label input_label top_select_input_label" for="category-custom-select">Category</label>
                                    </div>
                                  </div>
                                  <div class="col-md-6 input_wrapper">
                                    <div class="form-group bmd-form-group is-filled">
                                      <label for="subcategory_name" class="bmd-label-floating input_label">Sub Category Name *</label>
                                      <input type="text" class="form-control form_input_field" id="category_name" name="subcategory_name" required="true" aria-required="true" value="{{$subcat->subcategory_name}}">
                                    </div>
                                  </div>
                                </div>


                    <fieldset class="custom_fieldset_2">
                      <legend class="resource_para_label">Add Parameter for Resource</legend>

                  @if(!$unit_params->isEmpty())
                    @foreach($unit_params as $rowdata)
                   
                      <div class="row input_row unit_parameter_row">
                        
                        
                        
                        <div class="col-md-5 input_wrapper first">
                          <div class="form-group bmd-form-group">
                            <label for="unit_parameter_name" class="bmd-label-floating input_label">Name of parameter *</label>
                            <input type="hidden" name="unit_param_key[]" value="{{$rowdata->id}}">
                            <input type="text" class="form-control form_input_field" id="unit_parameter_name" name="unit_param_name[]" required="true" aria-required="true" value="{{$rowdata->unit_param_name}}">
                          </div>
                        </div>
                        <div class="col-md-5 second input_wrapper custom_select2_col">
                          <div class="form-group  custom-form-select">
                            <select class="custom-select unit_parameter_type select2 form_input_field hasvalue" id="unit_data_type" name="unit_param_data_type[]" required="true" aria-required="true">
                              <option class="form-select-placeholder"></option>
                              <option value="string" @if($rowdata->unit_param_data_type == 'string') selected @endif>String</option>
                              <option value="integer" @if($rowdata->unit_param_data_type == 'integer') selected @endif>Integer</option>
                              <option value="decimal" @if($rowdata->unit_param_data_type == 'decimal') selected @endif>Decimal</option>
                              <option value="datetime" @if($rowdata->unit_param_data_type == 'datetime') selected @endif>DateTime</option>
                              <option value="checkbox" @if($rowdata->unit_param_data_type == 'checkbox') selected @endif>Checkbox</option>
                              <option value="vin_number" @if($rowdata->unit_param_data_type == 'vin_number') selected @endif>VIN Number</option>
                              <option value="upc_number" @if($rowdata->unit_param_data_type == 'upc_number') selected @endif>UPC Number</option>
                            </select>
                            <div class="form-element-bar">
                            </div>
                            <label class="form-element-label" for="unit_data_type input_label">Data Type</label>
                          </div>
                        </div>
                          <div class="col-md-2 unit_parameter_cross text-right">
                              <a href="#" class="btn btn-link btn-danger btn-just-icon remove unit_param_dlt_btn"><i class="material-icons">close</i><div class="ripple-container"></div></a>
                          </div>
                      </div>
                    @endforeach
                  @else
                    <div class="row input_row unit_parameter_row">
                        <div class="col-md-5 input_wrapper first">
                          <div class="form-group bmd-form-group">
                            <label for="unit_parameter_name" class="bmd-label-floating input_label">Name of parameter *</label>
                            <input type="text" class="form-control form_input_field" id="unit_parameter_name" name="unit_param_name[]" required="true" aria-required="true">
                          </div>
                        </div>
                        <div class="col-md-5 second input_wrapper custom_select2_col">
                          <div class="form-group  custom-form-select">
                            <select class="custom-select unit_parameter_type select2 form_input_field" id="unit_data_type" name="unit_param_data_type[]" required="true" aria-required="true">
                              <option class="form-select-placeholder"></option>
                              <option value="string">String</option>
                              <option value="integer">Integer</option>
                              <option value="decimal">Decimal</option>
                              <option value="datetime">DateTime</option>
                              <option value="checkbox">Checkbox</option>
                              <option value="vin_number">VIN Number</option>
                              <option value="upc_number">UPC Number</option>
                            </select>
                            <div class="form-element-bar">
                            </div>
                            <label class="form-element-label" for="unit_data_type input_label">Data Type</label>
                          </div>
                        </div>
                          <div class="col-md-2 unit_parameter_cross text-right">
                              <a href="#" class="btn btn-link btn-danger btn-just-icon remove disabled"><i class="material-icons">close</i><div class="ripple-container"></div></a>
                          </div>
                      </div>
                  @endif

                      <div class="row add_parameter_btn_row">
                          <div class="col-md-12 text-right">
                            <button class="btn btn-info btn-round btn-sm add_parameter_btn" type="button">
                              <span class="btn-label">
                                <i class="material-icons">add</i>
                              </span>
                              Add Parameter
                              <div class="ripple-container"></div>
                            </button>
                          </div>
                      </div>
                  </fieldset>

                              <div class="form-group bmd-form-group save_btn_wrapper text-right">
                                <button type="submit" class="btn save_btn custom-btn-one">Update</button>
                              </div>
                          </form>
                          </div>
                      </div>


                     
                  </div>
                </div>
  
  
  
                </div>
              </div>
          </div>
        </div>
      </div>

@endsection