routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return redirect()->route('home');
});*/

Auth::routes();

// Route::get('/test',function(){
// 	return App\User::find(1)->profile;
// });
// Route::get('/', 'HomeController@index')->name('home');
// Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/oil_field', 'HomeController@home')->name('home');


Route::get('/', 'HomeController@home')->name('home');
Route::get('/home', 'HomeController@home')->name('home');
Route::get('/oil_field', 'HomeController@home')->name('home');


Route::resource('/users', 'admin\UserController');
Route::get('/myProfile', 'admin\UserController@myProfile')->name('myProfile');
Route::post('/myProfile', 'admin\UserController@myProfileUpdate')->name('myProfileUpdate');

Route::resource('/settings', 'admin\SettingsController');

Route::resource('/inventory', 'admin\InventoryController');
Route::post('/getSubcategory', 'admin\InventoryController@getSubcategory')->name('getSubcategory');
Route::post('/getInventoryInfo', 'admin\InventoryController@getInventoryInfo')->name('getInventoryInfo');
Route::post('/getResourceInfoBySubcat', 'admin\InventoryController@getResourceInfoBySubcat')->name('getResourceInfoBySubcat');
Route::post('/getVariablesBySubcat', 'admin\InventoryController@getVariablesBySubcat')->name('getVariablesBySubcat');
Route::post('/getImagesBySubcat', 'admin\InventoryController@getImagesBySubcat')->name('getImagesBySubcat');
Route::post('/getUnitDetailsBySubcat', 'admin\InventoryController@getUnitDetailsBySubcat')->name('getUnitDetailsBySubcat');
Route::post('/unitProperties', 'admin\InventoryController@unitProperties')->name('unitProperties');
Route::post('/unitPropertiesDlt', 'admin\InventoryController@unitPropertiesDlt')->name('unitPropertiesDlt');


Route::resource('/customers', 'admin\CustomerController');
Route::get('/qbCallback', 'admin\CustomerController@qbCallback');
Route::get('/qbCustomer', 'admin\CustomerController@qbCustomer')->name('qbCustomer');
Route::get('/qbRefreshToken', 'admin\CustomerController@qbRefreshToken')->name('qbRefreshToken');
Route::post('/importQbData', 'admin\CustomerController@importQbData')->name('importQbData');
Route::get('/synchronizeCustomer', 'admin\CustomerController@synchronizeCustomer')->name('synchronizeCustomer');
Route::get('/synchronizeQb', 'admin\CustomerController@synchronizeQb')->name('synchronizeQb');
Route::get('/insertQbCustomer', 'admin\CustomerController@insertQbCustomer')->name('insertQbCustomer');
Route::get('/discardQbCustomer', 'admin\CustomerController@discardQbCustomer')->name('discardQbCustomer');
Route::get('/singleCustomerQB', 'admin\CustomerController@singleCustomerQB')->name('singleCustomerQB');

Route::get('/creditApp/{id}/edit', 'admin\CustomerController@creditAppEdit')->name('creditAppEdit');
Route::get('/creditApp/{id}', 'admin\CustomerController@creditAppShow')->name('creditAppShow');
Route::post('/creditAppUpdate', 'admin\CustomerController@creditAppUpdate')->name('creditAppUpdate');
Route::get('/creditAppDelete/{id}', 'admin\CustomerController@creditAppDelete')->name('creditAppDelete');
Route::get('creditApp/accessCode/{token}', 'admin\CustomerController@creditAppToken');
Route::post('creditApp', 'admin\CustomerController@creditAppCustomer')->name('creditAppCustomer');
Route::post('creditAppUpdateForCustomer', 'admin\CustomerController@creditAppUpdateForCustomer')->name('creditAppUpdateForCustomer');
Route::get('creditAppMessage', 'admin\CustomerController@creditAppMessage')->name('creditAppMessage');
Route::get('creditAppPdf/{id}', 'admin\CustomerController@creditAppPdf')->name('creditAppPdf');



Route::resource('/products', 'admin\ProductController');

Route::resource('/vendors', 'admin\VendorController');
Route::get('/getQbVendor', 'admin\VendorController@getQbVendor')->name('getQbVendor');
Route::get('/synchronizeEvosVendor', 'admin\VendorController@synchronizeEvosVendor')->name('synchronizeEvosVendor');
Route::get('/synchronizeQbVendor', 'admin\VendorController@synchronizeQbVendor')->name('synchronizeQbVendor');
Route::get('/insertQbVendor', 'admin\VendorController@insertQbVendor')->name('insertQbVendor');
Route::get('/discardQbVendor', 'admin\VendorController@discardQbVendor')->name('discardQbVendor');


Route::post('/getImage', 'admin\VendorController@getImage')->name('getImage');

Route::resource('/quotation', 'admin\QuotationController');

Route::post('/getService', 'admin\QuotationController@getService')->name('getService');

Route::post('/getServiceResourceInfo', 'admin\QuotationController@getServiceResourceInfo')->name('getServiceResourceInfo');
Route::post('/getRentalResourceInfo', 'admin\QuotationController@getRentalResourceInfo')->name('getRentalResourceInfo');
Route::post('/getAddress', 'admin\QuotationController@getAddress')->name('getAddress');

Route::post('/addVariableSection', 'admin\InventoryController@addVariableSection')->name('addVariableSection');

Route::post('/variableEnableDisable', 'admin\InventoryController@variableEnableDisable')->name('variableEnableDisable');


Route::post('/getCustomerDetails', 'admin\QuotationController@getCustomerDetails')->name('getCustomerDetails');
Route::post('/updateCustomerQuoteInfo', 'admin\QuotationController@updateCustomerQuoteInfo')->name('updateCustomerQuoteInfo');

Route::resource('/insurance', 'admin\InsuranceController');
Route::get('insurance/accessCode/{token}', 'admin\InsuranceController@insuranceToken');
Route::post('insurance/pdf', 'admin\InsuranceController@getPdf')->name('getPdf');
Route::post('findInsurance', 'admin\InsuranceController@findInsurance')->name('findInsurance');
Route::post('generateInsuranceReport', 'admin\InsuranceController@generateInsuranceReport')->name('generateInsuranceReport');
Route::post('agreement', 'admin\InsuranceController@agreement')->name('agreement');
Route::get('agreementMessage', 'admin\InsuranceController@agreementMessage')->name('agreementMessage');
Route::post('getInsuranceImage', 'admin\InsuranceController@getInsuranceImage')->name('getInsuranceImage');
Route::post('generateAgreementReport', 'admin\InsuranceController@generateAgreementReport')->name('generateAgreementReport');
Route::get('agreementPdf/{id}', 'admin\InsuranceController@agreementPdf')->name('agreementPdf');
Route::post('/autocomplete', 'admin\InsuranceController@autocomplete')->name('autocomplete');



Route::post('deleteInventoryUnit', 'admin\InventoryController@deleteInventoryUnit')->name('deleteInventoryUnit');

Route::get('test', 'admin\InventoryController@test')->name('test');

Route::get('agreement', 'admin\InsuranceController@agreement')->name('agreement');

Route::get('subcontractor_pdf', 'admin\InsuranceController@subcontractor_pdf')->name('subcontractor_pdf');
Route::get('rental_pdf', 'admin\InsuranceController@rental_pdf')->name('rental_pdf');
Route::get('owner_pdf', 'admin\InsuranceController@owner_pdf')->name('owner_pdf');

Route::get('creditApplication', 'admin\CustomerController@creditApplication')->name('creditApplication');
Route::get('creditApplicationEmail', 'admin\CustomerController@creditApplicationEmail')->name('creditApplicationEmail');
Route::get('creditApplicationPdf', 'admin\CustomerController@creditApplicationPdf')->name('creditApplicationPdf');

Route::resource('/jobChecklist', 'admin\JobChecklistController');


Route::get('/users/make_admin/{id}','admin\UserController@make_admin')->name('make.admin');
Route::get('/users/make_agent/{id}','admin\UserController@make_agent')->name('make.agent');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;


class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone_no', 'status', 'role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];


    public function getRouteKeyName()
    {
        return 'name';
    }

    public function profile(){
        return $this->hasOne('App\Models\Profile');
    }
}

app/Http/Controllers/admin/UserController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use App\User;

class UserController extends Controller
{   
    public function __construct()
    {
        $this->middleware('auth');
        $this->middleware('admin');
    }

	public function index(){
	    $users = User::all();
        return view('admin.user.index', compact('users'));
	}
    

    public function create(){
    	return view('admin.user.create');
    }

    
    public function store(Request $request){

    	$request->validate([
            'name' => 'required|unique:users',
            'email' => 'required|unique:users',
            'password' => 'required',
        ]);

    	$user = new User([
    		'name' => $request->name,
    		'email' => $request->email,
    		'password' => bcrypt($request->password),
    		'phone_no' => $request->phone_no,
    		'status' => $request->status == 'on' ? 'active' : 'inactive',
    		'role' => $request->role == 'on' ? 'admin' : 'agent',
		]);
 
        $user->save();

        session()->flash('success', 'Successfully added');

        return back();

    }

    
    public function show(){
    	//
    }

    
    public function edit($name){
        //$user = User::find($id);
        $user = User::where('name',$name)->first();
        return view('admin.user.edit', compact('user'));
    }

    
     public function update(Request $request, $id){
     	$user = User::find($id);

        $user->phone_no = $request->phone_no;
        $user->status = $request->status == 'on' ? 'active' : 'inactive';
        $user->role = $request->role == 'on' ? 'admin' : 'agent';

        if($request->password){
            $user->password = bcrypt($request->password);
        }

        $user->update();

        session()->flash('success', 'Successfully updated');
        return redirect()->route('users.index');
    }

    
     public function destroy(User $user){
     	$user->delete();
        session()->flash('success', 'Successfully deleted');
        return back();
    }


    public function myProfile(){

        $user = auth()->user();
        return view('admin.user.myProfile', compact('user'));
    }


    public function myProfileUpdate(Request $request){

        $user = auth()->user();
        
        $myProfile = User::where('id', $user->id)->first();

        $myProfile->phone_no = $request->phone_no;
        $myProfile->status = $request->status == 'on' ? 'active' : 'inactive';
        $myProfile->role = $request->role == 'on' ? 'admin' : 'agent';

        if($request->password){
            $myProfile->password = bcrypt($request->password);
        }

        $myProfile->update();

        session()->flash('success', 'You have successfully updated your profile');

        return back();
    }


    public function make_admin($id){
        $user = User::find($id);

        $user->role = 'admin';
        $user->save();

        session()->flash('success', 'Successfully changed the role');
        return redirect()->back();
    }


    public function make_agent($id){
        $user = User::find($id);

        $user->role = 'agent';
        $user->save();

        session()->flash('success', 'Successfully changed the role');
        return redirect()->back();
    }


}

resources/views/admin/user/create.blade.php
@extends('layouts.master')

@section('content')


<div class="content">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <form id="add_user_form" action="{{ route('users.store') }}" method="post">

                        @csrf

                        <div class="card ">
                            <div class="card-header card-header-rose card-header-icon user_sub_card">
                                <div class="card-icon">
                                    <i class="material-icons">face</i>
                                </div>
                                <h4 class="card-title box_label_title">Add User</h4>
                            </div>

                            <div style="margin-top: 15px;">
                                @include('partials.messages')
                            </div>

                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group bmd-form-group">
                                            <label for="user_name" class="bmd-label-floating input_label"> User Name *</label>
                                            <input type="text" class="form-control form_input_field" id="user_name" name="name" required aria-required="true">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group bmd-form-group">
                                            <label for="user_email" class="bmd-label-floating input_label"> Email Address *</label>
                                            <input type="email" class="form-control form_input_field" id="user_email" name="email" required="true" aria-required="true">
                                        </div>
                                    </div>
                                </div>
                                <div class="row input_row">
                                    <div class="col-md-6">
                                        <div class="form-group bmd-form-group">
                                            <label for="user_password" class="bmd-label-floating input_label"> Password *</label>
                                            <input type="password" class="form-control form_input_field" id="user_password" name="password" required="true" name="password" aria-required="true" autocomplete="new-password">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group bmd-form-group">
                                            <label for="user_phone" class="bmd-label-floating input_label"> Phone number</label>
                                            <input type="text" class="form-control form_input_field" id="user_phone" name="phone_no">
                                        </div>
                                    </div>
                                </div>
                                <div class="row user_stat_role">
                                    <div class="col-md-6">
                                        <div class="form-group bmd-form-group">
                                            <h5 class="title">Status</h5>
                                            <div class="togglebutton user_stat_toggle">
                                                <label>
                                                    <input type="checkbox" name="status" checked=""> Inactive &nbsp; <span class="toggle"></span> Active
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                    <div class="form-group bmd-form-group">
                                      <h5 class="title">Role</h5>
                                      <div class="togglebutton admin-role-toggle">
                                        <label>
                                            <input type="checkbox" name="role" checked="">
                                            Agent <span class="toggle"></span> Admin
                                        </label>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                            </div>
                            <div class="card-footer text-right ml-auto save_btn_wrapper">
                                <button type="submit" class="btn custom-btn-one save_btn">Register</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.master')

@section('content')


<div class="content">
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-8 mx-auto">
                    <form id="add_user_form" action="{{ route('users.update', $user->id) }}" method="post">

                        @csrf
                        @method('PUT')

                        <div class="card ">
                            <div class="card-header card-header-rose card-header-icon user_sub_card">
                                <div class="card-icon">
                                    <i class="material-icons">face</i>
                                </div>
                                <h4 class="card-title">Edit User</h4>
                            </div>

                            <div style="margin-top: 15px;">
                                @include('partials.messages')
                            </div>

                            <div class="card-body ">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="form-group bmd-form-group is-filled">
                                            <label for="user_name" class="bmd-label-floating input_label"> User Name</label>
                                            <input type="text" class="form-control form_input_field" id="user_name" name="name" required aria-required="true" value="{{$user->name}}" disabled="">
                                        </div>
                                    </div>
                                    <div class="col-md-6 input_wrapper">
                                        <div class="form-group bmd-form-group is-filled">
                                            <label for="user_email" class="bmd-label-floating input_label"> Email Address</label>
                                            <input type="email" class="form-control form_input_field" id="user_email" name="email" required="true" aria-required="true" value="{{$user->email}}" disabled>
                                        </div>
                                    </div>
                                </div>
                                <div class="row input_row">
                                    <div class="col-md-6 input_wrapper">
                                        <div class="form-group bmd-form-group">
                                            <label for="user_password" class="bmd-label-floating input_label"> Password </label>
                                            <input type="password" class="form-control form_input_field" id="user_password" name="password" autocomplete="new-password">
                                        </div>
                                    </div>
                                    <div class="col-md-6 input_wrapper">
                                        <div class="form-group bmd-form-group is-filled">
                                            <label for="user_phone" class="bmd-label-floating input_label"> Phone number </label>
                                            <input type="text" class="form-control form_input_field" id="user_phone" name="phone_no" value="{{$user->phone_no}}">
                                        </div>
                                    </div>
                                </div>
                                <div class="row user_stat_role">
                                    <div class="col-md-6 input_wrapper">
                                        <div class="form-group bmd-form-group">
                                            <h5 class="title">Status</h5>
                                            <div class="togglebutton">
                                                <label>
                                                    <input type="checkbox" name="status" @if($user->status == 'active') checked @endif> Inactive <span class="toggle"></span> Active
                                                </label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-md-6 input_wrapper">
                                    <div class="form-group bmd-form-group">
                                      <h5 class="title">Role</h5>
                                      <div class="togglebutton admin-role-toggle">
                                        <label>
                                            <input type="checkbox" name="role" @if($user->role == 'admin') checked @endif>
                                            Agent <span class="toggle"></span> Admin
                                        </label>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                            </div>
                            <div class="card-footer text-right ml-auto save_btn_wrapper">
                                <button type="submit" class="btn custom-btn-one save_btn">Update</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.master')

@section('content')      


      <div class="content">
        <div class="content">
          <div class="container-fluid">
            <div class="row">
              <div class="col-md-12">

                  

                  <div class="card">
                    <div class="card-header card-header-rose card-header-icon user_sub_card">
                      <div class="card-icon">
                        <i class="material-icons">face</i>
                      </div>
                      <h4 class="card-title">All Users</h4>
                    </div>

                    <div style="margin-top: 15px;">
                        @include('partials.messages')
                    </div>

                    <div class="card-body">
                      <div class="toolbar">
                      </div>
                      <div class="material-datatables user_datatable">
                        <table id="all_users_table" class="table table-striped table-no-bordered table-hover all_table" cellspacing="0" width="100%" style="width:100%;">
                          <thead>
                            <tr>
                              <th>User Name</th>
                              <th>Email</th>
                              <th>Phone</th>
                              <th>Role</th>
                              <th>Status</th>
                              <th class="text-right">Change Status</th>
                              <th class="disabled-sorting text-right">Actions</th>
                            </tr>
                          </thead>

                          <tbody>

                          @foreach($users as $rowdata)
                            <tr>
                              <td>{{$rowdata->name}}</td>
                              <td>{{$rowdata->email}}</td>
                              <td>{{$rowdata->phone_no}}</td>
                              <td>{{$rowdata->status}}</td>
                              <td>{{$rowdata->role}}</td>
                              @if($rowdata->role == 'admin')
                              <td class="text-left"> <a href=" {{ route('make.agent', ['id'=> $rowdata->id]) }} " class="btn btn-sm btn-link btn-warning">Make Agent</a></td>
                              @else
                              <td class="text-left"> <a href="{{ route('make.admin', ['id'=> $rowdata->id]) }} " class="btn btn-sm btn-link btn-success">Make Admin</a></td>
                              @endif

                              <td class="text-right">
                                
                                <form action="{{ route('users.destroy',$rowdata->id) }}" method="POST">
                                    <a href="{{ route('users.edit',$rowdata->name) }}" class="btn btn-link btn-success btn-just-icon edit"><i class="material-icons">edit</i></a>
                                 
                                    @csrf
                                    @method('DELETE')
                    
                                    <button type="submit" class="btn btn-link btn-danger btn-just-icon remove" onclick="return confirm('Are you sure you want to delete?');"><i class="material-icons">close</i></button>
                                </form>
                              
                              </td>
                            </tr>
                          @endforeach
                          
                          </tbody>
                        </table>
                      </div>
                    </div>
                    <!-- end content-->
                  </div>


                
              </div>
            </div>
        </div>
      </div>
    </div>

@endsection

<script>
  $(window).on('load', function(){
    setTimeout(function() {
       $('.material-datatables').css('overflow-x','unset');
       $('.user_datatable table thead th:last-child').css('width','100px');
    }, 100);
  });
</script>